version: '3.9'
services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto
    image: filipnet/mosquitto:${TAG}
    #cpus: 1.5
    #mem_limit: 2048m
    ports:
      - "${MQTT_PORT}:1883/tcp"
    environment:
      - TAG=latest
      - MQTT_PORT=1883
