version: '3.9'
services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto
    image: filipnet/mosquitto:latest
    #cpus: 1.5
    #mem_limit: 2048m
    ports:
      - "1883:1883/tcp"
